import org.overlord.bam.activity.model.ActivityTypeRef
import org.overlord.bam.analytics.service.ResponseTime
import org.overlord.bam.analytics.Situation

global org.overlord.bam.epn.cep.EPNContext epn

declare ResponseTime
    @role( event )
end

rule "check for SLA violations"
when
    $rt : ResponseTime() from entry-point "ServiceResponseTimes" 
then

	if ($rt.getAverage() > 200) {
		epn.logError("\r\n\r\n**** RESPONSE TIME "+$rt.getAverage()+"ms EXCEEDED SLA FOR "+$rt.getServiceType()+" ****\r\n");
		
		Situation situation=new Situation();
		
		situation.setType("SLA Violation");
		situation.setSubject($rt.getServiceType()+"/"+$rt.getOperation());
		situation.setTimestamp(System.currentTimeMillis());
		
		if ($rt.getAverage() > 400) {
			situation.setDescription("Service exceeded maximum response time of 400 ms");
			situation.setSeverity(Situation.Severity.Critical);
		} else if ($rt.getAverage() > 320) {
			situation.setDescription("Service exceeded response time of 320 ms");
			situation.setSeverity(Situation.Severity.High);
		} else if ($rt.getAverage() > 260) {
			situation.setDescription("Service exceeded response time of 260 ms");
			situation.setSeverity(Situation.Severity.Medium);
		} else {
			situation.setDescription("Service exceeded response time of 200 ms");
			situation.setSeverity(Situation.Severity.Low);
		}
		
		epn.forward(situation);
	}	

end
