import org.overlord.bam.activity.model.ActivityTypeRef
import org.overlord.bam.service.analytics.ResponseTime
import org.overlord.bam.service.analytics.SLAViolation

global org.overlord.bam.epn.cep.EPNContext epn

declare ResponseTime
    @role( event )
end

rule "check for SLA violations"
when
    $rt : ResponseTime() from entry-point "ResponseTimes" 
then

	if ($rt.getDuration() > 1000) {
		epn.logError("\r\n\r\n**** RESPONSE TIME "+$rt.getDuration()+"ms EXCEEDED SLA FOR "+$rt.getServiceType()+" ****\r\n");
		
		SLAViolation sv=new SLAViolation();
		
		sv.setServiceType($rt.getServiceType());
		sv.setOperation($rt.getOperation());
		sv.setTimestamp(System.currentTimeMillis());
		
		if ($rt.getDuration() > 400) {
			sv.setViolation("Service exceeded maximum response time of 400 ms");
			sv.setSeverity("Critical");
		} else {
			sv.setViolation("Service exceeded maximum response time of 200 ms");
			sv.setSeverity("Medium");
		}
		
		epn.forward(sv);
	}	

end
